space_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: space
      host: localhost
      port: 8123
      user: default
      password: ""
      secure: False
      verify: False
      driver: http
